version: "3.8"
services:
    node-app:
      build: .
       # context: ./dockerfiles -- this 2 lines get use when we have our dockerfile in different directory
        # dockerfile: Dockerfile
      ports:
        - "3000:3000"
